constraint_groups:
- id: code_quality
  name: Code Quality Standards
  description: Basic code quality and best practices
  icon: 🔧
  color: '#4CAF50'
- id: security
  name: Security Requirements
  description: Security-focused constraints and vulnerability prevention
  icon: 🔒
  color: '#F44336'
- id: architecture
  name: Architecture Guidelines
  description: Development practices and architectural standards
  icon: 🏗️
  color: '#2196F3'
- id: plantuml
  name: PlantUML Standards
  description: Diagram creation and PlantUML workflow standards
  icon: 📊
  color: '#9C27B0'
- id: documentation
  name: Documentation Standards
  description: Documentation format and organization requirements
  icon: 📚
  color: '#FF9800'
- id: framework_specific
  name: Framework-Specific Rules
  description: Framework and library specific constraints (can be enabled per project)
  icon: ⚛️
  color: '#607D8B'
constraints:
- id: no-console-log
  group: code_quality
  pattern: console\.log
  message: Use Logger.log() instead of console.log for better log management
  severity: error
  enabled: true
  file_pattern: '\.(js|ts|jsx|tsx|mjs|cjs)$'
  suggestion: 'Replace with: Logger.log(''info'', ''category'', message)'
  whitelist:
  - '**/.claude/plans/*.md'
- id: no-var-declarations
  group: code_quality
  pattern: \bvar\s+
  message: Use 'let' or 'const' instead of 'var'
  severity: warning
  enabled: true
  suggestion: Use 'let' for mutable variables, 'const' for immutable
- id: proper-error-handling
  group: code_quality
  pattern: catch\s*\([^)]*\)\s*\{\s*\}
  message: Empty catch blocks should be avoided
  severity: error
  enabled: true
  suggestion: Add proper error handling or at minimum log the error
- id: proper-function-naming
  group: code_quality
  pattern: function\s+[a-z]
  message: Function names should start with a verb (camelCase)
  severity: info
  enabled: true
  suggestion: 'Use descriptive verb-based names: getUserData(), processResults()'
- id: no-magic-numbers
  group: code_quality
  pattern: \b\d{2,}\b(?!\s*(px|%|em|rem|vh|vw))
  message: Magic numbers detected - consider using named constants
  severity: info
  enabled: true
  suggestion: 'Define meaningful constants: const MAX_RETRIES = 3'
- id: no-hardcoded-secrets
  group: security
  pattern: (api[_-]?key|password|secret|token)\s*[=:]\s*['"][^'"]{8,}['"]
  message: Potential hardcoded secret detected
  severity: critical
  enabled: true
  suggestion: Use environment variables or secure key management
  semantic_validation: true
- id: no-eval-usage
  group: security
  pattern: \beval\s*\(
  message: eval() usage detected - security risk
  severity: critical
  enabled: true
  suggestion: Avoid eval() - use safer alternatives for dynamic code execution
- id: no-parallel-files
  group: architecture
  pattern: (v[2-9]|enhanced|improved|better|new|advanced|pro|simplified|simple|basic|lite|fixed|patched|updated|revised|modified|temp|temporary|backup|copy|duplicate|clone|alt|alternative|variant|final|draft|experimental|old)[ ._-]
  message: 'CRITICAL: No parallel versions allowed - edit the original file directly'
  severity: critical
  enabled: true
  applies_to: file_path
  tool_filter:
  - Write
  suggestion: Debug and fix the original file instead of creating parallel versions
- id: debug-not-speculate
  group: architecture
  pattern: (maybe|probably|might be|could be|seems like|appears to be).*(?:error|issue|problem|bug)
  message: Always debug and verify - never speculate about issues
  severity: error
  enabled: true
  suggestion: Use debugging tools and verification commands to identify root causes
  semantic_validation: true
- id: no-evolutionary-names
  group: architecture
  # Pattern requires evolutionary word to NOT be preceded or followed by lowercase letters
  # This prevents false positives like "isInFinalization", "entityLastUpdated", "processTestResults"
  # The (?<![a-z]) ensures the word isn't embedded in camelCase (like lastUpdated)
  pattern: (?:class|function|const|let|var)\s+\w*(?<![a-z])(?:V[2-9]|Enhanced|Improved|Better|New|Advanced|Pro|Simplified|Simple|Basic|Lite|Fixed|Patched|Updated|Revised|Modified|Temp|Temporary|Backup|Copy|Duplicate|Clone|Alt|Alternative|Variant|Final|Draft|Experimental)(?![a-z])
  message: Evolutionary naming detected - refactor original instead. (Whitelisted
    files are exempt from this rule)
  severity: error
  enabled: true
  suggestion: Rename to descriptive functional name and refactor the original
  semantic_validation: false
  whitelist:
  - scripts/enhanced-transcript-monitor.js
  - scripts/enhanced-*.js
- id: no-backup-files
  group: architecture
  pattern: \.(backup|bak|old|orig|tmp)(-\d{8}(-\d{6})?)?$
  message: 'CRITICAL: Backup files prohibited in development - use git for versioning'
  severity: critical
  enabled: true
  suggestion: Remove backup files and commit changes to git instead. Use 'git diff'
    to compare versions.
- id: knowledge-base-direct-manipulation
  group: architecture
  pattern: (?:\.data/knowledge-(?:export|graph)/|\.data/knowledge-export/.*\.json)
  message: 'CRITICAL: Knowledge base must only be manipulated through bin/ukb CLI'
  severity: critical
  enabled: true
  applies_to: file_path
  suggestion: Use 'bin/ukb' CLI for all knowledge base operations. Never directly
    edit files in .data/knowledge-export/ or .data/knowledge-graph/
- id: plantuml-standard-styling
  group: plantuml
  pattern: '@startuml.*\n(?!.*!include _standard-style\.puml)'
  message: PlantUML files must include the standard styling file
  severity: error
  enabled: true
  suggestion: Add '!include _standard-style.puml' after @startuml and before content
  whitelist:
  # Fixed: Use **/ prefix for proper glob matching on full paths
  - '**/*.yaml'
  - '**/*.yml'
  - '**/.constraint-monitor.yaml'
- id: plantuml-file-location
  group: plantuml
  pattern: '!include.*\.puml'
  message: PlantUML files should be stored in docs/puml/ directory
  severity: warning
  enabled: true
  suggestion: Move .puml files to docs/puml/ and update !include paths
- id: plantuml-diagram-workflow
  group: plantuml
  pattern: (?i)(architecture|diagram|flow|sequence).*(?:diagram|chart)
  message: 'Diagrams should follow PlantUML workflow: .puml files in docs/puml/, PNG
    files in docs/images/'
  severity: info
  enabled: true
  suggestion: 1. Create .puml file in docs/puml/ with !include _standard-style.puml
    2. Generate PNG with plantuml -tpng 3. Store PNG in docs/images/ 4. Reference
    PNG in markdown
- id: plantuml-readability-guidelines
  group: plantuml
  pattern: (?i)(too wide|barely readable|restructure.*readability)
  message: PlantUML diagrams should prioritize readability with vertical layouts and
    logical grouping
  severity: info
  enabled: true
  suggestion: Use 'skinparam direction top to bottom layout' and group related components
    in rectangles or packages
- id: plantuml-file-organization
  group: plantuml
  pattern: \.puml$
  message: 'PlantUML files should follow naming convention: component-purpose.puml'
  severity: info
  enabled: true
  suggestion: Use descriptive names like workflow-sequence.puml, architecture-overview.puml
- id: plantuml-no-incremental-filenames
  group: plantuml
  pattern: '[-_](?:2|3|v2|v3|new|updated|revised|final|copy)\.(puml|png)$'
  message: 'CRITICAL: Incremental naming in diagrams is forbidden - modify the original file instead of creating versioned copies'
  severity: critical
  enabled: true
  applies_to: filename
  suggestion: Instead of creating diagram-name-2.puml, edit diagram-name.puml directly
- id: plantuml-diagram-name-format
  group: plantuml
  # Fixed: Changed \s to [ \t] to avoid matching newlines (which caused false positives on multi-line files)
  pattern: '@startuml\s+(?:[A-Z]|[^\n]*[ \t][^\n]*|[^\n]*(?:v[2-9]|enhanced|improved|better|new|advanced|pro|simplified|simple|basic|lite|fixed|patched|updated|revised|modified|temp|temporary|backup|copy|duplicate|clone|alt|alternative|variant|final|draft|experimental|old)[ ._-])'
  message: 'CRITICAL: @startuml diagram name must be lowercase-hyphenated without spaces or version suffixes (determines output PNG filename)'
  severity: critical
  enabled: true
  applies_to: content
  suggestion: 'Change @startuml My Diagram Name to @startuml my-diagram-name (must match filename without .puml extension)'
- id: image-reference-pattern
  group: documentation
  pattern: '!\[.*\]\((?!docs/images/).*\.(png|jpg|jpeg|svg)\)'
  message: Diagram images should be stored in docs/images/ and referenced with relative
    paths
  severity: warning
  enabled: true
  suggestion: 'Move images to docs/images/ and update markdown references: ![Description](docs/images/filename.png)'
- id: documentation-filename-format
  group: documentation
  pattern: '(?:[A-Z][a-z]+[A-Z]|[A-Z]{2,}).*\.md$'
  message: 'Documentation files should use kebab-case naming: feature-name.md (only README.md and CHANGELOG.md may use uppercase)'
  severity: error
  enabled: true
  applies_to: file_path
  suggestion: 'Rename to kebab-case: my-feature-docs.md instead of MyFeatureDocs.md or ALL-CAPS-FILE.md'
  whitelist:
  # Fixed: Use **/ prefix for proper glob matching on full paths
  - '**/README.md'
  - '**/CHANGELOG.md'
  - '**/CLAUDE.md'
  - '**/INSTALL*.md'
  - CLAUDE.md
- id: update-main-readme
  group: documentation
  pattern: (?i)readme.*(?:update|modify|change).*(?:structure|format|content)
  message: Main README updates should maintain consistent structure and TOC
  severity: info
  enabled: true
  suggestion: 'Follow established README sections: Purpose, Features, Installation,
    Usage, Architecture'
- id: no-incremental-documentation
  group: documentation
  pattern: (?i)\b(fixed|improved|added|updated|changed|modified|removed|deprecated|enhanced|new|now|recent|recently|previous|previously|old|older|formerly|originally|was|were|used
    to be)\s+(in|on|for|during|as of)?\s*(jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec|january|february|march|april|june|july|august|september|october|november|december)?\s*\d{4}\b|\b(dec|nov|oct|sep|aug|jul|jun|may|apr|mar|feb|jan)\s*\d{4}\b|(?:since|as of|in|from)\s+v\d+\.\d+|version\s+\d+\.\d+\s+(?:added|changed|fixed|updated)|\(fixed\)|\(added\)|\(improved\)|\(updated\)
  message: 'CRITICAL: Documentation describes CURRENT state only - no version history,
    fix dates, or incremental language. Use git for history.'
  severity: error
  enabled: true
  applies_to: content
  tool_filter:
  - Edit
  - Write
  file_pattern: \.md$
  suggestion: Remove dates and incremental language. Describe how the system works
    NOW, not when it changed. Git provides version history.
  whitelist:
  - CHANGELOG.md
  - RELEASE*.md
- id: no-ascii-art-in-docs
  group: documentation
  pattern: '[┌┐└┘│─├┤┬┴┼▲▼◄►]'
  message: 'CRITICAL: ASCII/line art detected in documentation - use PlantUML diagrams
    instead. You MUST invoke documentation-style skill FIRST'
  severity: error
  enabled: true
  file_pattern: '\.md$'
  suggestion: 1. Invoke Skill tool with skill='documentation-style' 2. Create .puml
    file in docs/puml/ 3. Generate PNG with plantuml 4. Reference image in markdown
  whitelist:
  - '**/.claude/plans/*.md'
- id: documentation-style-skill-required
  group: documentation
  pattern: (?:```(?:plantuml|puml|mermaid)|@startuml|flowchart|sequenceDiagram)
  message: 'CRITICAL: Creating diagrams requires documentation-style skill. You MUST
    invoke Skill tool with skill=''documentation-style'' BEFORE creating diagram files'
  severity: error
  enabled: true
  applies_to: file_path
  suggestion: 'STOP: Invoke the documentation-style skill first: Use Skill tool with
    parameter skill=''documentation-style'' to load proper workflow and standards'
  whitelist:
  - .constraint-monitor.yaml
- id: plantuml-modification-requires-skill
  group: plantuml
  pattern: '@startuml|!include.*\.puml'
  message: 'CRITICAL: Modifying PlantUML files requires documentation-style skill.
    You MUST invoke Skill tool with skill=''documentation-style'' FIRST'
  severity: error
  enabled: true
  applies_to: content
  tool_filter:
  - Edit
  - Write
  - mcp__serena__replace_symbol_body
  - mcp__serena__insert_after_symbol
  - mcp__serena__insert_before_symbol
  file_pattern: \.puml$
  suggestion: 'STOP: Invoke the documentation-style skill first: Use Skill tool with
    parameter skill=''documentation-style'' to load PlantUML workflow, validation,
    and PNG generation standards'
  whitelist:
  - .constraint-monitor.yaml
- id: plantuml-png-outdated
  group: plantuml
  description: PlantUML PNG files must be regenerated after .puml modifications
  severity: warning
  enabled: true
  validation_type: post_file_edit
  file_pattern: \.puml$
  check_type: file_timestamp_comparison
  png_path_pattern: '{{dirname}}/{{basename}}.png'
  max_age_seconds: 120
  message: 'PlantUML source file was modified but corresponding PNG file is outdated
    or missing.


    PUML file: {{file_path}}

    Expected PNG: {{png_path}}


    ACTION REQUIRED:

    1. Generate PNG: plantuml {{file_path}}

    2. Move to images: mv {{dirname}}/{{basename}}.png docs/images/

    3. Verify PNG exists and is up-to-date


    The PNG file must be updated within 120 seconds of the .puml modification.

    '
  suggestion: 'Run: plantuml {{file_path}} && mv {{dirname}}/{{basename}}.png docs/images/'
- id: react-hooks-deps
  group: framework_specific
  pattern: useEffect\([^,]*,\s*\[\]
  message: useEffect with empty deps array - verify if this is intentional
  severity: info
  enabled: true
  suggestion: Ensure useEffect dependencies are correct to avoid bugs
- id: react-state-complexity
  group: framework_specific
  pattern: useState\([^)]*\{[^}]*\}[^)]*\)
  message: Complex object in useState - consider useReducer or separate states
  severity: warning
  enabled: true
  suggestion: Use useReducer for complex state or separate into multiple useState
    calls
- id: no-java-jar-plantuml
  group: plantuml
  pattern: java\s+.*-jar\s+.*plantuml
  message: 'CRITICAL: Never use java -jar plantuml.jar! Always use the plantuml CLI
    command directly: plantuml <file.puml>'
  severity: critical
  enabled: true
  applies_to: content
  tool_filter:
  - Bash
  suggestion: 'Use the plantuml CLI: plantuml docs/puml/my-diagram.puml (NOT java
    -jar plantuml.jar)'
- id: no-ukb-bash-command
  group: architecture
  pattern: ^ukb\s|^ukb$|\s+ukb\s|\s+ukb$|[;&|]\s*ukb\s|[;&|]\s*ukb$
  message: 'CRITICAL: ''ukb'' is NOT a shell command! When user types ''ukb'' at Claude
    prompt, call MCP semantic analysis tool (full or incremental), NOT bash'
  severity: critical
  enabled: true
  applies_to: content
  tool_filter:
  - Bash
  suggestion: 'User typing ''ukb'' at Claude prompt means: Call mcp-server-semantic-analysis
    tool (full or incremental workflow). Never try to run ''ukb'' as a bash/shell
    command - it was completely removed from the system.'
  semantic_validation: true
settings:
  compliance:
    excellent_threshold: 9
    good_threshold: 7
    warning_threshold: 5
  risk_levels:
    critical_violations_for_high_risk: 1
    error_violations_for_medium_risk: 3
    warning_violations_for_low_risk: 10
  monitoring:
    cache_timeout: 5000
    max_history: 1000
    auto_cleanup: true
  groups:
    show_empty_groups: false
    collapse_disabled_groups: true
    sort_by_severity: true
enforcement:
  enabled: true
  blocking_levels:
  - critical
  - error
  warning_levels:
  - warning
  info_levels:
  - info
  fail_open: true
