/**
 * The publish step must not be able to destroy hand-written analysis.
 *
 * THE INCIDENT THIS PINS. `docs/benchmarks/coding-v1/README.md` held 632 lines of
 * hand-written analysis built around the generated tables: the embedded charts, the full
 * question set with its ground truth, the fourteen measurement defects found while building
 * the benchmark, and the reasoning that makes the numbers mean anything. The documented way
 * to publish was to render the report and copy it over that path, which replaces all of it
 * with the machine version.
 *
 * It happened twice. At f6bb7875c, 619 lines went in a commit whose message is entirely
 * about an answer key and never mentions the report. Again on 2026-08-09, in a commit that
 * described the report as having GROWN — true against the already-collapsed file, and the
 * reason nobody caught it either time.
 *
 * The file carried a warning about precisely this, under "Reproduce it". The warning lived
 * inside the file it was warning about, so the first clobber destroyed the warning too.
 * That is why this is a test and an exit code rather than a sentence in a document: prose
 * inside the blast radius is not a control.
 */

import { mkdtempSync, writeFileSync, readFileSync, existsSync, rmSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import path from 'node:path';
import os from 'node:os';

// jest's ESM VM leaves import.meta.dirname undefined; the sibling kgbench suites all take
// the repo root from cwd, which jest sets to the project root.
const REPO = process.cwd();
const SCRIPT = path.join(REPO, 'scripts/kgbench-report.mjs');
const RUN = 'coding-v1-x2';
/** The run docs/benchmarks/coding-v1 currently describes. Moves with the published page. */
const PUBLISHED_RUN = 'coding-v1-r8';

/** Run the reporter, returning {status, stderr} instead of throwing on refusal. */
const render = (outPath, extra = []) => {
  try {
    const stdout = execFileSync('node', [SCRIPT, '--run', RUN, '--out', outPath, ...extra],
      { cwd: REPO, encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] });
    return { status: 0, stdout, stderr: '' };
  } catch (err) {
    return { status: err.status ?? 1, stdout: String(err.stdout ?? ''), stderr: String(err.stderr ?? '') };
  }
};

describe('kgbench-report --out refuses to overwrite a file it did not write', () => {
  let dir;
  beforeEach(() => { dir = mkdtempSync(path.join(os.tmpdir(), 'kgb-publish-')); });
  afterEach(() => rmSync(dir, { recursive: true, force: true }));

  it('refuses a hand-written target, and leaves it byte-identical', () => {
    const target = path.join(dir, 'README.md');
    const prose = '# Code-retrieval benchmark\n\nHand-written analysis nobody can regenerate.\n';
    writeFileSync(target, prose);

    const res = render(target);

    expect(res.status).toBe(2);
    expect(res.stderr).toMatch(/refusing to overwrite/);
    expect(readFileSync(target, 'utf8')).toBe(prose);
  });

  it('says where generated output should go, so the refusal is actionable', () => {
    const target = path.join(dir, 'README.md');
    writeFileSync(target, '# hand-written\n');
    expect(render(target).stderr).toMatch(/RESULTS\.md/);
  });

  it('writes a new file happily — the guard is about clobbering, not about writing', () => {
    const target = path.join(dir, 'RESULTS.md');
    expect(render(target).status).toBe(0);
    expect(existsSync(target)).toBe(true);
  });

  it('overwrites its OWN previous output, so re-rendering stays a no-friction loop', () => {
    const target = path.join(dir, 'RESULTS.md');
    expect(render(target).status).toBe(0);
    const first = readFileSync(target, 'utf8');
    expect(first).toContain('GENERATED by scripts/kgbench-report.mjs');
    // Second render must not need --force: the marker identifies the file as machine-owned.
    expect(render(target).status).toBe(0);
  });

  it('honours --force, because a deliberate replacement must remain possible', () => {
    const target = path.join(dir, 'README.md');
    writeFileSync(target, '# hand-written\n');
    expect(render(target, ['--force']).status).toBe(0);
    expect(readFileSync(target, 'utf8')).toContain('GENERATED by scripts/kgbench-report.mjs');
  });
});

describe('the published coding-v1 pair keeps its roles straight', () => {
  const dir = path.join(REPO, 'docs/benchmarks/coding-v1');

  it('README.md is hand-written — no generated marker', () => {
    const md = readFileSync(path.join(dir, 'README.md'), 'utf8');
    expect(md).not.toContain('GENERATED by scripts/kgbench-report.mjs');
  });

  it('RESULTS.md is generated — carries the marker on line 1', () => {
    const md = readFileSync(path.join(dir, 'RESULTS.md'), 'utf8');
    expect(md.split('\n')[0]).toContain('GENERATED by scripts/kgbench-report.mjs');
  });

  it('README links to the generated numbers rather than restating them', () => {
    expect(readFileSync(path.join(dir, 'README.md'), 'utf8')).toContain('RESULTS.md');
  });
});

/**
 * A published row's clock must cover the attempts it says it made.
 *
 * THE DEFECT THIS PINS. `runCell` spread the LAST attempt's result onto the row, so a retried cell
 * reported that attempt's `wall_s` beside an `attempts` array listing every attempt — 35.6s next to
 * a list summing to 73.6s. The row contradicted itself in plain sight and nothing objected.
 *
 * This is a SHAPE check over whatever run is currently published, not a value check: it cannot tell
 * you the number is right, only that the row is no longer self-contradicting. That is enough to
 * stop the old row shape being republished.
 */
describe('a published row accounts for its own attempts', () => {
  const RESULTS = path.join(REPO, '.data/kgbench/runs', PUBLISHED_RUN, 'results.jsonl');

  it('wall_s is at least the sum of its attempts', () => {
    if (!existsSync(RESULTS)) {
      // Run data is gitignored. Absent on a fresh clone; present wherever it matters.
      return;
    }
    const rows = readFileSync(RESULTS, 'utf8').trim().split('\n').map((l) => JSON.parse(l));
    const short = rows
      .filter((r) => Array.isArray(r.attempts) && r.attempts.length > 1)
      .map((r) => ({
        cell: `${r.arm}/${r.agent}/${r.id} rep${r.rep}`,
        wall_s: r.wall_s,
        // 0.05 absorbs the per-attempt toFixed(1) rounding, nothing more.
        attempts_wall_s: +r.attempts.reduce((a, x) => a + (x.wall_s ?? 0), 0).toFixed(1),
      }))
      .filter((x) => x.wall_s + 0.05 < x.attempts_wall_s);
    expect(short).toEqual([]);
  });
});
