// PATTERN SOURCE: 45-PATTERNS.md § FilterRail.tsx (Phase 45 baseline)
//   + 55-08-PLAN.md Task 3 (Phase 55 rewire)
//   + 55-PATTERNS.md § FilterRail mount order
// CONTRACT: 45-UI-SPEC.md § Layout Contract row 3 (w-64 / w-12 collapsed)
//
// MOUNT ORDER SUPERSEDED 2026-09-25. 55-UI-SPEC.md §6 pinned a flat order —
// Search → LayerFilter → DomainFilter → OntologyFilter → GraphToggles →
// TrendingPanel → HierarchyNavigator — and the rail grew to 1818px of content
// in an 855px viewport: 53% below the fold, with the legend last and collapsed.
// Eleven sections, five different collapse idioms, and four checkboxes that all
// answered "how much detail?" with two opposite polarities.
//
// The order is now: Search → DetailLevel → Legend → Advanced → Navigators.
// Nothing was removed. Everything previously in the rail is inside one of the
// two accordions, which start collapsed, so the default view fits without
// scrolling. Recording the supersession here rather than silently diverging
// from the spec it names.
//
// Phase 45 → Phase 55 deltas:
//   - The Phase 45 flat ClassList is REMOVED. The new VOKB-shape grouped
//     OntologyFilter replaces it (UI-SPEC §6 mandate).
//   - LayerFilter, DomainFilter, OntologyFilter, GraphToggles are mounted
//     in UI-SPEC §6 top-to-bottom order.
//   - This file OWNS the lazy mount lines for TrendingPanel and
//     HierarchyNavigator. Plans 55-10 / 55-11 OVERWRITE the placeholder
//     modules at the imported paths but DO NOT edit this file.
//   - Two new required props: `system` (drives the OntologyFilter schema
//     and HierarchyNavigator coding-only gate) and `entities` (counts are
//     derived from this list inside the filter children).

import { useEffect, useRef, lazy, Suspense, type ReactNode } from 'react'
import { ChevronLeft, ChevronRight, Filter } from 'lucide-react'
import type { ApiClient } from '@/api/ApiClient'
import type { Entity } from '@/api/ApiClient'
import type { HierarchyEdge } from '@/graph/hierarchy-parents'
import type { System } from '@/config/system-endpoints'
import { Checkbox } from '@/components/ui/checkbox'
import { IconButton } from '@/components/IconButton'
import { useViewerStore, type Level } from '@/store/viewer-store'
import { Logger } from '@/lib/logging'
import { LayerFilter } from '@/panels/filters/LayerFilter'
import { LearningSourceFilter } from '@/panels/filters/LearningSourceFilter'
import { TeamsFilter } from '@/panels/filters/TeamsFilter'
import { DomainFilter } from '@/panels/filters/DomainFilter'
import {
  OntologyFilter,
  VOKB_SCHEMA,
} from '@/panels/filters/OntologyFilter'
import { ContentToggles, StructureToggles } from '@/panels/filters/GraphToggles'
import { DetailLevel } from '@/panels/filters/DetailLevel'
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from '@/components/ui/accordion'

// Lazy mounts pinned by Plan 55-08 (closes plan-checker B-2 + B-3).
// Plan 55-10 Task 1 OVERWRITES ./TrendingPanel; Plan 55-11 Task 1
// OVERWRITES ./coding/HierarchyNavigator. This file MUST NOT be edited
// by those downstream plans — they only overwrite the imported files.
const TrendingPanel = lazy(() => import('./TrendingPanel'))
const HierarchyNavigator = lazy(() => import('./coding/HierarchyNavigator'))
// Lazy like its neighbours: it categorises every rendered row against the whole
// entity list, and it is collapsed by default, so none of that should run for
// an operator who never opens it.
const GraphQualityPanel = lazy(() => import('./GraphQualityPanel'))

export interface FilterRailProps {
  apiClient: ApiClient
  /**
   * Ontology classes derived from the actual entity payload — historical
   * Phase 45 prop. Still threaded for backwards compatibility with
   * UnifiedViewer.tsx; downstream consumers will be retired in a later
   * plan once the prop is no longer referenced.
   */
  classOptions: readonly string[]
  /** Returned from useKeyboardShortcuts so `/` focuses our search input. */
  registerSearchInputRef: (input: HTMLInputElement | null) => void
  /** Current system; chooses OntologyFilter schema and gates
   * HierarchyNavigator (coding-only). */
  system: System
  /** Entity array — child filter components derive count badges. */
  entities: readonly Entity[]
  /**
   * Edge set. Only the HierarchyNavigator needs it: the tree's parent pointers
   * come from `contains` / `parent-child` / `includes` edges, because the
   * `metadata.parent` field it used to read has never been written by anything.
   */
  relations?: readonly HierarchyEdge[]
  /** Phase 55 — slot for the LegendPanel (or any other end-of-rail surface).
   * Mounted at the BOTTOM of the vertical stack per UI-SPEC §6 row 12. */
  bottomSlot?: ReactNode
  /** Nodes currently rendered — same predicate the canvas and footer use. */
  /** Ids currently rendered. Passed rather than derived: UnifiedViewer already
   *  computes this from `useGraphVisibility`, and a second derivation here
   *  would be exactly the drift that hook exists to prevent. */
  visibleIds?: ReadonlySet<string>
  visibleCount?: number
  /** Rendered rows with no Project/System above them. See graph/unanchored.ts. */
  unanchoredCount?: number
}

const LEVELS: ReadonlyArray<{ value: Level; label: string }> = [
  { value: 0, label: 'L0' },
  { value: 1, label: 'L1' },
  { value: 2, label: 'L2' },
  { value: 3, label: 'L3' },
]

export function FilterRail({
  apiClient,
  classOptions: _classOptions,
  registerSearchInputRef,
  system,
  entities,
  relations,
  bottomSlot,
  visibleIds,
  visibleCount,
  unanchoredCount,
}: FilterRailProps) {
  const searchQuery = useViewerStore((s) => s.searchQuery)
  const setSearch = useViewerStore((s) => s.setSearch)
  const visibleLevels = useViewerStore((s) => s.visibleLevels)
  const toggleLevel = useViewerStore((s) => s.toggleLevel)
  const setVisibleLevels = useViewerStore((s) => s.setVisibleLevels)
  const collapsed = useViewerStore((s) => s.filterRailCollapsed)
  const setCollapsed = useViewerStore((s) => s.setFilterRailCollapsed)

  const searchInputRef = useRef<HTMLInputElement | null>(null)
  useEffect(() => {
    registerSearchInputRef(searchInputRef.current)
    return () => registerSearchInputRef(null)
  }, [registerSearchInputRef])

  // One-shot mount log per 55-08 Task 3.
  useEffect(() => {
    Logger.info(Logger.Categories.PANELS, 'FilterRail mounted')
  }, [])

  const widthClass = collapsed ? 'w-12' : 'w-64'

  if (collapsed) {
    return (
      <aside
        data-testid="viewer-filter-rail"
        className={`${widthClass} bg-card border-r border-border p-2 flex flex-col items-center gap-2`}
      >
        <IconButton
          icon={ChevronRight}
          ariaLabel="Show filters"
          onClick={() => {
            setCollapsed(false)
            Logger.info(Logger.Categories.FILTERS, 'Filter rail expanded')
          }}
          data-testid="filter-rail-toggle"
        />
        <Filter className="h-4 w-4 text-muted-foreground" aria-hidden />
      </aside>
    )
  }

  // Phase 60 (60-05): OntologyFilter schema choice flipped. Coding tab now
  // omits the prop entirely so OntologyFilter takes its API-driven path
  // (L1->L2 groups from /api/v1/ontology/classes?withDisplay=true). OKB tab
  // keeps the legacy hardcoded path via VOKB_SCHEMA — W-1 regression
  // preservation (VOKB schema migration is explicitly out of Phase 60 scope).
  const legacyGroupingSchema = system === 'okb' ? VOKB_SCHEMA : undefined

  return (
    <aside
      data-testid="viewer-filter-rail"
      className={`${widthClass} bg-card border-r border-border p-4 overflow-y-auto space-y-4`}
    >
      <div className="flex items-center justify-between">
        <div className="text-xs font-medium uppercase tracking-wide text-muted-foreground">
          Filters
        </div>
        <IconButton
          icon={ChevronLeft}
          ariaLabel="Hide filters"
          onClick={() => {
            setCollapsed(true)
            Logger.info(Logger.Categories.FILTERS, 'Filter rail collapsed')
          }}
          data-testid="filter-rail-toggle"
        />
      </div>

      {/* Search (Phase 45 BC) */}
      <div>
        <input
          ref={searchInputRef}
          value={searchQuery}
          onChange={(e) => {
            setSearch(e.target.value)
            Logger.debug(Logger.Categories.FILTERS, `Search: "${e.target.value}"`)
          }}
          placeholder="Search entities..."
          data-testid="filter-search"
          aria-label="Search by name or description (/)"
          className="h-9 w-full min-w-0 rounded-md border border-input bg-transparent px-3 py-1 text-sm shadow-xs outline-none placeholder:text-muted-foreground focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50"
        />
      </div>

      {/* ── ESSENTIALS — everything above the fold ────────────────────────
          One question ("how much detail?"), then the key to the canvas. The
          three switches DetailLevel writes live in Advanced > Structure. */}
      <DetailLevel visibleCount={visibleCount} unanchoredCount={unanchoredCount} />

      {/* The legend was the LAST thing in the rail and collapsed by default,
          which put the key to the colours below ~960px of filters. It is what a
          reader needs first, so it sits here now. */}
      {bottomSlot}

      {/* ── ADVANCED — one collapsed section, four groups ─────────────────
          Everything that was previously stacked flat in the rail. Nothing was
          removed; it is one click away instead of one scroll away. The rail
          used to carry FIVE different collapse idioms (useState+triangle, a
          useState record, shadcn Collapsible, shadcn Accordion and native
          <details>); this is the one idiom for all of it. */}
      <Accordion type="multiple" className="w-full" data-testid="filter-advanced">
        <AccordionItem value="scope">
          <AccordionTrigger className="text-xs py-2" data-testid="filter-advanced-scope">
            Scope
          </AccordionTrigger>
          <AccordionContent className="space-y-4 pt-1">
            <TeamsFilter entities={entities} apiClient={apiClient} />

      {/* Level (Phase 45 BC) */}
      <div className="space-y-2">
        <div className="flex items-center justify-between">
          <div className="text-xs font-medium text-muted-foreground">Level</div>
          <SelectAllNone
            allLabel="All"
            noneLabel="None"
            onAll={() => {
              setVisibleLevels(new Set<Level>([0, 1, 2, 3]))
              Logger.info(Logger.Categories.FILTERS, 'Selected all levels')
            }}
            onNone={() => {
              setVisibleLevels(new Set<Level>())
              Logger.info(Logger.Categories.FILTERS, 'Cleared all levels')
            }}
          />
        </div>
        <div className="space-y-1">
          {LEVELS.map(({ value, label }) => {
            const checked = visibleLevels.has(value)
            return (
              <label
                key={value}
                className="flex items-center gap-2 text-sm cursor-pointer"
                data-testid={`filter-level-${value}`}
              >
                <Checkbox
                  checked={checked}
                  onCheckedChange={() => {
                    toggleLevel(value)
                    Logger.info(
                      Logger.Categories.FILTERS,
                      `Level ${label} ${checked ? 'hidden' : 'shown'}`,
                    )
                  }}
                  aria-label={label}
                />
                <span>{label}</span>
              </label>
            )
          })}
        </div>
      </div>

            {/* Layer (Evidence/Pattern) — the OKB/km-core LearningArtifact
                `defaultLayer` axis, NOT a coding-KG-native concept (in VKB it
                just means Insight=pattern, everything else=evidence). Hidden in
                the VKB tab per operator 2026-06-19; kept for OKB/VOKB. */}
            {system !== 'coding' && <LayerFilter entities={entities} />}

            {/* Renders nothing when the system has no domains — it used to
                render the sentence "Domain filter not applicable for this
                system", which is a filter-shaped hole in the rail. */}
            <DomainFilter entities={entities} />

            {/* Ontology Class — grouped tree (REPLACES the Phase 45 flat
                ClassList). Phase 60 (60-05): the coding tab uses the API-driven
                L1->L2 path (no prop); OKB pins legacyGroupingSchema={VOKB_SCHEMA}
                to keep its Upper/Lower groups (W-1 regression preservation). */}
            <OntologyFilter
              entities={entities}
              apiClient={apiClient}
              groupingSchema={legacyGroupingSchema}
            />
          </AccordionContent>
        </AccordionItem>

        <AccordionItem value="source">
          <AccordionTrigger className="text-xs py-2" data-testid="filter-advanced-source">
            Knowledge source
          </AccordionTrigger>
          <AccordionContent className="pt-1">
            <LearningSourceFilter />
          </AccordionContent>
        </AccordionItem>

        <AccordionItem value="content">
          <AccordionTrigger className="text-xs py-2" data-testid="filter-advanced-content">
            Content
          </AccordionTrigger>
          <AccordionContent className="pt-1">
            <ContentToggles />
          </AccordionContent>
        </AccordionItem>

        <AccordionItem value="structure">
          <AccordionTrigger className="text-xs py-2" data-testid="filter-advanced-structure">
            Structure
          </AccordionTrigger>
          <AccordionContent className="pt-1">
            <StructureToggles />
          </AccordionContent>
        </AccordionItem>
      </Accordion>

      {/* ── NAVIGATORS — not filters; they move you around the graph ───────
          Collapsed by default. Trending was ~500px of always-open list and the
          hierarchy tree is unbounded, which is most of why the rail scrolled. */}
      <Accordion type="multiple" className="w-full" data-testid="filter-navigators">
        <AccordionItem value="trending">
          <AccordionTrigger className="text-xs py-2" data-testid="filter-nav-trending">
            Trending insights
          </AccordionTrigger>
          <AccordionContent className="pt-1">
            <Suspense
              fallback={
                <div
                  data-testid="trending-panel-fallback"
                  className="text-xs text-muted-foreground px-3 py-2"
                >
                  Loading trending…
                </div>
              }
            >
              <TrendingPanel apiClient={apiClient} />
            </Suspense>
          </AccordionContent>
        </AccordionItem>

        {system === 'coding' && (
          <AccordionItem value="hierarchy">
            <AccordionTrigger className="text-xs py-2" data-testid="filter-nav-hierarchy">
              Hierarchy
            </AccordionTrigger>
            <AccordionContent className="pt-1">
              <Suspense
                fallback={
                  <div
                    data-testid="hierarchy-navigator-fallback"
                    className="text-xs text-muted-foreground px-3 py-2"
                  >
                    Loading hierarchy…
                  </div>
                }
              >
                {/* 2026-09-08: `entities` was never passed. The navigator's
                    BC-shim falls back to `useViewerStore(s => s.entities)`, and
                    nothing has ever written that key — so this surface rendered
                    its "No hierarchy data yet" empty state permanently, on a
                    graph with 2441 entities in it. */}
                <HierarchyNavigator system={system} entities={entities} relations={relations} />
              </Suspense>
            </AccordionContent>
          </AccordionItem>
        )}

        <AccordionItem value="quality">
          <AccordionTrigger className="text-xs py-2" data-testid="filter-nav-quality">
            Graph quality
          </AccordionTrigger>
          <AccordionContent className="pt-1">
            <Suspense
              fallback={
                <div
                  data-testid="graph-quality-fallback"
                  className="text-xs text-muted-foreground px-3 py-2"
                >
                  Loading quality…
                </div>
              }
            >
              <GraphQualityPanel
                apiClient={apiClient}
                system={system}
                entities={entities}
                relations={relations ?? []}
                visibleIds={visibleIds ?? new Set<string>()}
              />
            </Suspense>
          </AccordionContent>
        </AccordionItem>
      </Accordion>

    </aside>
  )
}

interface SelectAllNoneProps {
  allLabel: string
  noneLabel: string
  disabled?: boolean
  onAll: () => void
  onNone: () => void
}

function SelectAllNone({
  allLabel,
  noneLabel,
  disabled,
  onAll,
  onNone,
}: SelectAllNoneProps) {
  // 2026-06-12: lowercase (matches Hierarchy / Typed Views subgroup
  // "all | none" links — was previously inconsistent with those).
  const base =
    'text-[10px] lowercase tracking-wide px-1.5 py-0.5 rounded ' +
    'text-muted-foreground hover:text-foreground hover:bg-accent ' +
    'disabled:opacity-40 disabled:cursor-not-allowed'
  return (
    <div className="flex items-center gap-1" data-testid="filter-select-all-none">
      <button
        type="button"
        onClick={onAll}
        disabled={disabled}
        className={base}
        aria-label={`Select ${allLabel}`}
      >
        {allLabel}
      </button>
      <span className="text-[10px] text-muted-foreground">·</span>
      <button
        type="button"
        onClick={onNone}
        disabled={disabled}
        className={base}
        aria-label={`Select ${noneLabel}`}
      >
        {noneLabel}
      </button>
    </div>
  )
}
