// PATTERN SOURCE: 45-PATTERNS.md § FilterRail.tsx (Phase 45 baseline)
//   + 55-08-PLAN.md Task 3 (Phase 55 rewire)
//   + 55-PATTERNS.md § FilterRail mount order
// CONTRACT: 45-UI-SPEC.md § Layout Contract row 3 (w-64 / w-12 collapsed)
//   + 55-UI-SPEC.md § 6 (mount order:
//     Search → LayerFilter → DomainFilter → OntologyFilter → GraphToggles
//     → TrendingPanel (lazy, always) → HierarchyNavigator (lazy, coding only))
//
// Phase 45 → Phase 55 deltas:
//   - The Phase 45 flat ClassList is REMOVED. The new VOKB-shape grouped
//     OntologyFilter replaces it (UI-SPEC §6 mandate).
//   - LayerFilter, DomainFilter, OntologyFilter, GraphToggles are mounted
//     in UI-SPEC §6 top-to-bottom order.
//   - This file OWNS the lazy mount lines for TrendingPanel and
//     HierarchyNavigator. Plans 55-10 / 55-11 OVERWRITE the placeholder
//     modules at the imported paths but DO NOT edit this file.
//   - Two new required props: `system` (drives the OntologyFilter schema
//     and HierarchyNavigator coding-only gate) and `entities` (counts are
//     derived from this list inside the filter children).

import { useEffect, useRef, lazy, Suspense } from 'react'
import { ChevronLeft, ChevronRight, Filter } from 'lucide-react'
import type { ApiClient } from '@/api/ApiClient'
import type { Entity } from '@/api/ApiClient'
import type { System } from '@/config/system-endpoints'
import { Checkbox } from '@/components/ui/checkbox'
import { IconButton } from '@/components/IconButton'
import { useViewerStore, type Level } from '@/store/viewer-store'
import { Logger } from '@/lib/logging'
import { LayerFilter } from '@/panels/filters/LayerFilter'
import { DomainFilter } from '@/panels/filters/DomainFilter'
import {
  OntologyFilter,
  CODING_SCHEMA,
} from '@/panels/filters/OntologyFilter'
import { GraphToggles } from '@/panels/filters/GraphToggles'

// Lazy mounts pinned by Plan 55-08 (closes plan-checker B-2 + B-3).
// Plan 55-10 Task 1 OVERWRITES ./TrendingPanel; Plan 55-11 Task 1
// OVERWRITES ./coding/HierarchyNavigator. This file MUST NOT be edited
// by those downstream plans — they only overwrite the imported files.
const TrendingPanel = lazy(() => import('./TrendingPanel'))
const HierarchyNavigator = lazy(() => import('./coding/HierarchyNavigator'))

export interface FilterRailProps {
  apiClient: ApiClient
  /**
   * Ontology classes derived from the actual entity payload — historical
   * Phase 45 prop. Still threaded for backwards compatibility with
   * UnifiedViewer.tsx; downstream consumers will be retired in a later
   * plan once the prop is no longer referenced.
   */
  classOptions: readonly string[]
  /** Returned from useKeyboardShortcuts so `/` focuses our search input. */
  registerSearchInputRef: (input: HTMLInputElement | null) => void
  /** Current system; chooses OntologyFilter schema and gates
   * HierarchyNavigator (coding-only). */
  system: System
  /** Entity array — child filter components derive count badges. */
  entities: readonly Entity[]
}

const LEVELS: ReadonlyArray<{ value: Level; label: string }> = [
  { value: 0, label: 'L0' },
  { value: 1, label: 'L1' },
  { value: 2, label: 'L2' },
  { value: 3, label: 'L3' },
]

export function FilterRail({
  apiClient,
  classOptions: _classOptions,
  registerSearchInputRef,
  system,
  entities,
}: FilterRailProps) {
  const searchQuery = useViewerStore((s) => s.searchQuery)
  const setSearch = useViewerStore((s) => s.setSearch)
  const visibleLevels = useViewerStore((s) => s.visibleLevels)
  const toggleLevel = useViewerStore((s) => s.toggleLevel)
  const setVisibleLevels = useViewerStore((s) => s.setVisibleLevels)
  const collapsed = useViewerStore((s) => s.filterRailCollapsed)
  const setCollapsed = useViewerStore((s) => s.setFilterRailCollapsed)

  const searchInputRef = useRef<HTMLInputElement | null>(null)
  useEffect(() => {
    registerSearchInputRef(searchInputRef.current)
    return () => registerSearchInputRef(null)
  }, [registerSearchInputRef])

  // One-shot mount log per 55-08 Task 3.
  useEffect(() => {
    Logger.info(Logger.Categories.PANELS, 'FilterRail mounted')
  }, [])

  const widthClass = collapsed ? 'w-12' : 'w-64'

  if (collapsed) {
    return (
      <aside
        data-testid="viewer-filter-rail"
        className={`${widthClass} bg-card border-r border-border p-2 flex flex-col items-center gap-2`}
      >
        <IconButton
          icon={ChevronRight}
          ariaLabel="Show filters"
          onClick={() => {
            setCollapsed(false)
            Logger.info(Logger.Categories.FILTERS, 'Filter rail expanded')
          }}
          data-testid="filter-rail-toggle"
        />
        <Filter className="h-4 w-4 text-muted-foreground" aria-hidden />
      </aside>
    )
  }

  // OntologyFilter schema is driven by system. Coding uses Hierarchy +
  // Typed Views; OKB uses the default VOKB Upper/Lower layout.
  const ontologySchema = system === 'coding' ? CODING_SCHEMA : undefined

  return (
    <aside
      data-testid="viewer-filter-rail"
      className={`${widthClass} bg-card border-r border-border p-4 overflow-y-auto space-y-4`}
    >
      <div className="flex items-center justify-between">
        <div className="text-xs font-medium uppercase tracking-wide text-muted-foreground">
          Filters
        </div>
        <IconButton
          icon={ChevronLeft}
          ariaLabel="Hide filters"
          onClick={() => {
            setCollapsed(true)
            Logger.info(Logger.Categories.FILTERS, 'Filter rail collapsed')
          }}
          data-testid="filter-rail-toggle"
        />
      </div>

      {/* Search (Phase 45 BC) */}
      <div>
        <input
          ref={searchInputRef}
          value={searchQuery}
          onChange={(e) => {
            setSearch(e.target.value)
            Logger.debug(Logger.Categories.FILTERS, `Search: "${e.target.value}"`)
          }}
          placeholder="Search entities..."
          data-testid="filter-search"
          aria-label="Search by name or description (/)"
          className="h-9 w-full min-w-0 rounded-md border border-input bg-transparent px-3 py-1 text-sm shadow-xs outline-none placeholder:text-muted-foreground focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50"
        />
      </div>

      {/* Level (Phase 45 BC) */}
      <div className="space-y-2">
        <div className="flex items-center justify-between">
          <div className="text-xs font-medium text-muted-foreground">Level</div>
          <SelectAllNone
            allLabel="All"
            noneLabel="None"
            onAll={() => {
              setVisibleLevels(new Set<Level>([0, 1, 2, 3]))
              Logger.info(Logger.Categories.FILTERS, 'Selected all levels')
            }}
            onNone={() => {
              setVisibleLevels(new Set<Level>())
              Logger.info(Logger.Categories.FILTERS, 'Cleared all levels')
            }}
          />
        </div>
        <div className="space-y-1">
          {LEVELS.map(({ value, label }) => {
            const checked = visibleLevels.has(value)
            return (
              <label
                key={value}
                className="flex items-center gap-2 text-sm cursor-pointer"
                data-testid={`filter-level-${value}`}
              >
                <Checkbox
                  checked={checked}
                  onCheckedChange={() => {
                    toggleLevel(value)
                    Logger.info(
                      Logger.Categories.FILTERS,
                      `Level ${label} ${checked ? 'hidden' : 'shown'}`,
                    )
                  }}
                  aria-label={label}
                />
                <span>{label}</span>
              </label>
            )
          })}
        </div>
      </div>

      {/* ---- Phase 55 NEW filter components (UI-SPEC §6 order) ---- */}

      {/* Layer (NEW) */}
      <LayerFilter entities={entities} />

      {/* Domain (NEW) */}
      <DomainFilter entities={entities} />

      {/* Ontology Class — grouped tree (NEW; REPLACES Phase 45 flat ClassList) */}
      <OntologyFilter entities={entities} groupingSchema={ontologySchema} />

      {/* Graph Toggles (NEW; ported from VOKB LegendPanel toggle block) */}
      <GraphToggles />

      {/* Trending Patterns — lazy mount, always rendered. Plan 55-10 ships the
          real component at ./TrendingPanel; until then a placeholder renders. */}
      <Suspense
        fallback={
          <div
            data-testid="trending-panel-fallback"
            className="text-xs text-muted-foreground px-3 py-2"
          >
            Loading trending…
          </div>
        }
      >
        <TrendingPanel apiClient={apiClient} />
      </Suspense>

      {/* Hierarchy Navigator — lazy mount, coding-only. Plan 55-11 ships the
          real component at ./coding/HierarchyNavigator; until then placeholder. */}
      {system === 'coding' && (
        <Suspense
          fallback={
            <div
              data-testid="hierarchy-navigator-fallback"
              className="text-xs text-muted-foreground px-3 py-2"
            >
              Loading hierarchy…
            </div>
          }
        >
          <HierarchyNavigator system={system} />
        </Suspense>
      )}
    </aside>
  )
}

interface SelectAllNoneProps {
  allLabel: string
  noneLabel: string
  disabled?: boolean
  onAll: () => void
  onNone: () => void
}

function SelectAllNone({
  allLabel,
  noneLabel,
  disabled,
  onAll,
  onNone,
}: SelectAllNoneProps) {
  const base =
    'text-[10px] uppercase tracking-wide px-1.5 py-0.5 rounded ' +
    'text-muted-foreground hover:text-foreground hover:bg-accent ' +
    'disabled:opacity-40 disabled:cursor-not-allowed'
  return (
    <div className="flex items-center gap-1" data-testid="filter-select-all-none">
      <button
        type="button"
        onClick={onAll}
        disabled={disabled}
        className={base}
        aria-label={`Select ${allLabel}`}
      >
        {allLabel}
      </button>
      <span className="text-[10px] text-muted-foreground">·</span>
      <button
        type="button"
        onClick={onNone}
        disabled={disabled}
        className={base}
        aria-label={`Select ${noneLabel}`}
      >
        {noneLabel}
      </button>
    </div>
  )
}
