#!/bin/bash
# generate-agent-instructions.sh
# Generates instruction files for non-Claude agents (Copilot, OpenCode)
# by combining CLAUDE.md rules with skill/command descriptions.
#
# All machine-specific paths (home dir, repo path, username) are replaced
# with portable placeholders so generated files can be committed.
#
# Usage:
#   ./scripts/generate-agent-instructions.sh [project_dir] [coding_repo]
#
# If no args given, uses current directory and auto-detects CODING_REPO.

set -euo pipefail

PROJECT_DIR="${1:-$(pwd)}"
CODING_REPO="${2:-${CODING_REPO:-$(cd "$(dirname "$0")/.." && pwd)}}"

COMMANDS_DIR="$CODING_REPO/.claude/commands"
CLAUDE_MD="$PROJECT_DIR/CLAUDE.md"

# ──────────────────────────────────────────────────────────────────────────────
# Helpers
# ──────────────────────────────────────────────────────────────────────────────

log() { echo "[agent-instructions] $*" >&2; }

# Replace machine-specific paths with portable placeholders
# Handles: home dir, repo absolute path, username
sanitize_paths() {
    local home_dir="$HOME"
    local username
    username=$(whoami)

    sed \
        -e "s|${CODING_REPO}|\$CODING_REPO|g" \
        -e "s|${home_dir}|~|g" \
        -e "s|/Users/${username}|~|g" \
        -e "s|/home/${username}|~|g"
}

# Extract multi-line description from YAML frontmatter (handles folded scalar >)
extract_description() {
    local file="$1"
    local in_fm=false in_desc=false desc=""

    while IFS= read -r line; do
        if [[ "$line" == "---" ]]; then
            if $in_fm; then break; fi
            in_fm=true
            continue
        fi
        if ! $in_fm; then continue; fi

        if [[ "$line" =~ ^description: ]]; then
            in_desc=true
            local val="${line#description:}"
            val="${val#"${val%%[![:space:]]*}"}"  # trim leading space
            if [[ "$val" != ">" && -n "$val" ]]; then
                desc="$val"
            fi
            continue
        fi

        if $in_desc; then
            # If line starts with a YAML key, we're past the description
            if [[ "$line" =~ ^[a-zA-Z_-]+: ]]; then
                break
            fi
            # Continuation of multi-line description
            local trimmed="${line#"${line%%[![:space:]]*}"}"
            if [[ -n "$trimmed" ]]; then
                desc="${desc:+$desc }$trimmed"
            fi
        fi
    done < "$file"
    echo "$desc"
}

# Emit skill list from .claude/commands/*.md
emit_skill_list() {
    local prefix="${1:-}"  # optional prefix for bullet lines (e.g. "/$name" vs "$name")
    for cmd_file in "$COMMANDS_DIR"/*.md; do
        [[ -f "$cmd_file" ]] || continue
        local name
        name=$(basename "$cmd_file" .md)
        local desc
        desc=$(extract_description "$cmd_file")
        if [[ -z "$desc" ]]; then
            # Fallback: use first non-empty, non-heading line
            desc=$(grep -v '^#\|^---\|^$' "$cmd_file" | head -1)
        fi
        echo "- **${prefix}${name}** (\`.claude/commands/$name.md\`): $desc"
    done
}

# ──────────────────────────────────────────────────────────────────────────────
# Generate .github/copilot-instructions.md
# ──────────────────────────────────────────────────────────────────────────────
generate_copilot_instructions() {
    local target_dir="$1"
    local github_dir="$target_dir/.github"
    local output="$github_dir/copilot-instructions.md"

    mkdir -p "$github_dir"

    {
        cat <<'HEADER'
<!-- AUTO-GENERATED by scripts/generate-agent-instructions.sh — do not edit manually -->
# Copilot Instructions

These instructions are generated from the project's CLAUDE.md and available skills
so that GitHub Copilot CLI follows the same conventions as other agents.

Paths shown as `$CODING_REPO` refer to the root of this repository.
Paths shown as `~` refer to the user's home directory.

HEADER

        # Include CLAUDE.md content (sanitize machine-specific paths)
        if [[ -f "$CLAUDE_MD" ]]; then
            echo "## Project Guidelines"
            echo ""
            # Skip the first H1 line and sanitize paths
            tail -n +2 "$CLAUDE_MD" | sanitize_paths
            echo ""
        fi

        # List available skills from .claude/commands/
        if [[ -d "$COMMANDS_DIR" ]]; then
            echo "## Available Skills"
            echo ""
            echo "The following skills are available. When a task matches a skill's description,"
            echo "read the full skill file and follow its instructions."
            echo ""
            emit_skill_list ""
            echo ""
        fi

    } > "$output"

    log "Generated $output"
}

# ──────────────────────────────────────────────────────────────────────────────
# Augment CLAUDE.md with skill references for OpenCode
# (OpenCode reads CLAUDE.md but doesn't have Claude's slash command system)
# ──────────────────────────────────────────────────────────────────────────────
ensure_skill_references_in_claude_md() {
    local claude_md="$1"

    [[ -f "$claude_md" ]] || return 0
    [[ -d "$COMMANDS_DIR" ]] || return 0

    local marker="## Available Skills (Auto-Generated)"

    # If marker already exists, replace the section; otherwise append
    if grep -qF "$marker" "$claude_md" 2>/dev/null; then
        # Remove old auto-generated section (from marker to next ## or EOF)
        local temp
        temp=$(mktemp)
        awk -v marker="$marker" '
            BEGIN { skip=0 }
            $0 == marker { skip=1; next }
            skip && /^## / { skip=0 }
            !skip { print }
        ' "$claude_md" > "$temp"
        mv "$temp" "$claude_md"
    fi

    # Append skill references
    {
        echo ""
        echo "$marker"
        echo ""
        echo "These skills are defined in \`.claude/commands/\` and provide reusable workflows."
        echo "Read the full skill file when a task matches its description."
        echo ""
        emit_skill_list "/"
        echo ""
    } >> "$claude_md"

    log "Updated skill references in $claude_md"
}

# ──────────────────────────────────────────────────────────────────────────────
# Main
# ──────────────────────────────────────────────────────────────────────────────
main() {
    local agent="${CODING_AGENT:-all}"

    log "Generating agent instructions (agent=$agent, project=$PROJECT_DIR)"

    case "$agent" in
        copilot)
            generate_copilot_instructions "$PROJECT_DIR"
            ;;
        opencode)
            ensure_skill_references_in_claude_md "$CLAUDE_MD"
            ;;
        claude)
            # Claude reads .claude/commands/ natively — nothing to generate
            log "Claude agent: no additional instructions needed"
            ;;
        all)
            generate_copilot_instructions "$PROJECT_DIR"
            # Only augment CLAUDE.md for non-coding projects (coding repo CLAUDE.md is manually managed)
            if [[ "$PROJECT_DIR" != "$CODING_REPO" ]]; then
                ensure_skill_references_in_claude_md "$CLAUDE_MD"
            fi
            ;;
    esac
}

main "$@"
