@startuml
!include _standard-style.puml

title Hierarchy Context: ConfigDrivenDesign

[CodingPatterns] as coding_patterns #FFFFDD
[ConfigDrivenDesign] as config_driven_design #LightBlue
[NamingConventions] as naming_conventions #F0F0F0
[ResilienceWrappers] as resilience_wrappers #F0F0F0

coding_patterns --> config_driven_design
naming_conventions -[hidden]- config_driven_design
resilience_wrappers -[hidden]- config_driven_design

@enduml