@startuml
!include _standard-style.puml

title Hierarchy Context: EntityMigrationPipeline

[KnowledgeManagement] as knowledge_management #FFFFDD
[EntityMigrationPipeline] as entity_migration_pipeline #LightBlue
[ManualLearning] as manual_learning #F0F0F0
[OnlineLearning] as online_learning #F0F0F0
[KMCoreStore] as kmcore_store #F0F0F0
[UKBTraceReporter] as ukbtrace_reporter #F0F0F0
[OntologyClassifier] as ontology_classifier #F0F0F0

knowledge_management --> entity_migration_pipeline
manual_learning -[hidden]- entity_migration_pipeline
online_learning -[hidden]- entity_migration_pipeline
kmcore_store -[hidden]- entity_migration_pipeline
ukbtrace_reporter -[hidden]- entity_migration_pipeline
ontology_classifier -[hidden]- entity_migration_pipeline

@enduml