@startuml
!include _standard-style.puml

title Hierarchy Context: GraphKnowledgeExporter

[KnowledgeManagement] as knowledge_management #FFFFDD
[GraphKnowledgeExporter] as graph_knowledge_exporter #LightBlue
[ManualLearning] as manual_learning #F0F0F0
[OnlineLearning] as online_learning #F0F0F0
[VkbApiClient] as vkb_api_client #F0F0F0
[CheckpointManager] as checkpoint_manager #F0F0F0
[GraphDatabaseAdapter] as graph_database_adapter #F0F0F0

knowledge_management --> graph_knowledge_exporter
manual_learning -[hidden]- graph_knowledge_exporter
online_learning -[hidden]- graph_knowledge_exporter
vkb_api_client -[hidden]- graph_knowledge_exporter
checkpoint_manager -[hidden]- graph_knowledge_exporter
graph_database_adapter -[hidden]- graph_knowledge_exporter

@enduml