@startuml
!include _standard-style.puml

title Hierarchy Context: ManualLearning

[KnowledgeManagement] as knowledge_management #FFFFDD
[ManualLearning] as manual_learning #LightBlue
[OnlineLearning] as online_learning #F0F0F0
[EntityMigrationScripts] as entity_migration_scripts #F0F0F0

knowledge_management --> manual_learning
online_learning -[hidden]- manual_learning
entity_migration_scripts -[hidden]- manual_learning

@enduml