@startuml
!include _standard-style.puml

title Hierarchy Context: OnlineLearning

[KnowledgeManagement] as knowledge_management #FFFFDD
[OnlineLearning] as online_learning #LightBlue
[ManualLearning] as manual_learning #F0F0F0
[VkbApiClient] as vkb_api_client #F0F0F0
[GraphKnowledgeExporter] as graph_knowledge_exporter #F0F0F0
[CheckpointManager] as checkpoint_manager #F0F0F0
[GraphDatabaseAdapter] as graph_database_adapter #F0F0F0

knowledge_management --> online_learning
manual_learning -[hidden]- online_learning
vkb_api_client -[hidden]- online_learning
graph_knowledge_exporter -[hidden]- online_learning
checkpoint_manager -[hidden]- online_learning
graph_database_adapter -[hidden]- online_learning

@enduml