@startuml
!include _standard-style.puml

title Hierarchy Context: Ontology

[SemanticAnalysis] as semantic_analysis #FFFFDD
[Ontology] as ontology #LightBlue
[Pipeline] as pipeline #F0F0F0
[Insights] as insights #F0F0F0

semantic_analysis --> ontology
pipeline -[hidden]- ontology
insights -[hidden]- ontology

@enduml