@startuml
!include _standard-style.puml

title Hierarchy Context: Pipeline

[SemanticAnalysis] as semantic_analysis #FFFFDD
[Pipeline] as pipeline #LightBlue
[Ontology] as ontology #F0F0F0
[Insights] as insights #F0F0F0
[OntologyRegistry] as ontology_registry #F0F0F0
[KmCoreAdapter] as km_core_adapter #F0F0F0
[TemplatMethodExecuteSequence] as templat_method_execute_sequence #E8F5E8

semantic_analysis --> pipeline
ontology -[hidden]- pipeline
insights -[hidden]- pipeline
ontology_registry -[hidden]- pipeline
km_core_adapter -[hidden]- pipeline
pipeline --> templat_method_execute_sequence

@enduml