@startuml
!include _standard-style.puml

title Hierarchy Context: ProcessStateManager

[DockerizedServices] as dockerized_services #FFFFDD
[ProcessStateManager] as process_state_manager #LightBlue
[HealthCoordinator] as health_coordinator #F0F0F0

dockerized_services --> process_state_manager
health_coordinator -[hidden]- process_state_manager

@enduml