@startuml
!include _standard-style.puml

title Hierarchy Context: ProxyUrlResolver

[LLMAbstraction] as llmabstraction #FFFFDD
[ProxyUrlResolver] as proxy_url_resolver #LightBlue

llmabstraction --> proxy_url_resolver

@enduml