@startuml
!include _standard-style.puml

title Hierarchy Context: ProxyURLResolver

[LLMAbstraction] as llmabstraction #FFFFDD
[ProxyURLResolver] as proxy_urlresolver #LightBlue
[LLMMockService] as llmmock_service #F0F0F0
[DMRProvider] as dmrprovider #F0F0F0
[LLMWithProcessClient] as llmwith_process_client #F0F0F0
[CostModel] as cost_model #F0F0F0

llmabstraction --> proxy_urlresolver
llmmock_service -[hidden]- proxy_urlresolver
dmrprovider -[hidden]- proxy_urlresolver
llmwith_process_client -[hidden]- proxy_urlresolver
cost_model -[hidden]- proxy_urlresolver

@enduml