@startuml
!include _standard-style.puml

title Hierarchy Context: ServiceStarter

[DockerizedServices] as dockerized_services #FFFFDD
[ServiceStarter] as service_starter #LightBlue
[ServiceProbe] as service_probe #F0F0F0
[ProcessStateManager] as process_state_manager #F0F0F0
[LLMMockService] as llmmock_service #F0F0F0
[HealthCoordinator] as health_coordinator #F0F0F0
[ServiceWrapperScripts] as service_wrapper_scripts #F0F0F0

dockerized_services --> service_starter
service_probe -[hidden]- service_starter
process_state_manager -[hidden]- service_starter
llmmock_service -[hidden]- service_starter
health_coordinator -[hidden]- service_starter
service_wrapper_scripts -[hidden]- service_starter

@enduml