@startuml
!include _standard-style.puml

title Hierarchy Context: UkbTraceReportGenerator

[KnowledgeManagement] as knowledge_management #FFFFDD
[UkbTraceReportGenerator] as ukb_trace_report_generator #LightBlue
[ManualLearning] as manual_learning #F0F0F0
[OnlineLearning] as online_learning #F0F0F0
[GraphDatabaseManager] as graph_database_manager #F0F0F0
[WaveAgentController] as wave_agent_controller #F0F0F0
[LlmServiceManager] as llm_service_manager #F0F0F0
[VkbApiClientManager] as vkb_api_client_manager #F0F0F0

knowledge_management --> ukb_trace_report_generator
manual_learning -[hidden]- ukb_trace_report_generator
online_learning -[hidden]- ukb_trace_report_generator
graph_database_manager -[hidden]- ukb_trace_report_generator
wave_agent_controller -[hidden]- ukb_trace_report_generator
llm_service_manager -[hidden]- ukb_trace_report_generator
vkb_api_client_manager -[hidden]- ukb_trace_report_generator

@enduml