@startuml
!include _standard-style.puml

title Hierarchy Context: VkbServer

[KnowledgeManagement] as knowledge_management #FFFFDD
[VkbServer] as vkb_server #LightBlue
[ManualLearning] as manual_learning #F0F0F0
[OnlineLearning] as online_learning #F0F0F0
[UkbUnifiedCli] as ukb_unified_cli #F0F0F0

knowledge_management --> vkb_server
manual_learning -[hidden]- vkb_server
online_learning -[hidden]- vkb_server
ukb_unified_cli -[hidden]- vkb_server

@enduml