@startuml
!include _standard-style.puml

title Hierarchy Context: VkbApiClient

[KnowledgeManagement] as knowledge_management #FFFFDD
[VkbApiClient] as vkb_api_client #LightBlue
[ManualLearning] as manual_learning #F0F0F0
[OnlineLearning] as online_learning #F0F0F0
[GraphKnowledgeExporter] as graph_knowledge_exporter #F0F0F0
[CheckpointManager] as checkpoint_manager #F0F0F0
[GraphDatabaseAdapter] as graph_database_adapter #F0F0F0

knowledge_management --> vkb_api_client
manual_learning -[hidden]- vkb_api_client
online_learning -[hidden]- vkb_api_client
graph_knowledge_exporter -[hidden]- vkb_api_client
checkpoint_manager -[hidden]- vkb_api_client
graph_database_adapter -[hidden]- vkb_api_client

@enduml